---
title: Pole Buoy
editor: 
  markdown: 
    wrap: 72
---

## Pole Buoy

The purpose of the pole buoy is to help track, find, and support the
drifting recorder. The pole buoy consists of;

1.  **Aluminum Pole:** 9' length, 1.25" 6063 aluminum round tube
2.  **Lead Weight:** approximately 17 lbs, attached to the bottom of the
    pole to keep buoy vertical
3.  **Crab Floats:** to keep pole buoy floating, with bolts above and
    below it to keep it from sliding along the pole
4.  **Bridle:** 12 strand line that links the pole buoy to the rest of
    the drifting recorder setup and arrray
5.  **Radar reflector:** so ships can see the pole buoy
6.  **GPS mount:** to hold the solar GPS and strobe light

![*Diagram of High Flyer Pole
Buoy*](images/Screenshot%202022-10-26%20092651.png){fig-align="left"}

### Pole Buoy Assembly

1.  Basic Assembly

    1.  Put crab floats on pole (flat ends to each other in the middle).
        Add tape, hose clamp or other temporary device to hold floats in
        place. If the center hole of the crab float is not wide enough
        to fit over the pole, an auger can be used to drill out the
        middle (ask for more help).

    2.  Add weights to one end of the pole at the very bottom. The pole
        mounted cylindrical weights should be drilled to fit the pole.
        Once this weight is secured in place, add the 5 lb flexible wire
        weight over the top of the pole weight.

    3.  Add radar reflector (first) and then insert the Solar GPS mount
        on top. Drill a hole through all three (pole, radar reflector,
        and gps mount) and use a thru-bolt to secure in place. Add a
        locking nut or electrical tape over the top of the nut to reduce
        chance of nut working itself loose.

    4.  Add reflector tape near the top of the buoy.

    5.  Add bridle to the pole buoy: 12 strand crab fishing line with
        2\@ hose for reducing wear on the line. Tie one end of the line
        around the pole buoy above the crab floats, and one below the
        crab floats (with the hose protecting where the line encircles
        the pole). Tie well and use zip ties to secure the line if
        needed. Put a loop in the middle of this line so that the
        surface floats can be clipped onto this loop using a caribiner.

2.  Float test

Put in calm water (at a marina or pool) to determine positioning of the
crab floats vertically on the pole. If the floats are too low, the buoy
will be unstable (pull the top of the pole over and see how well the
buoy rights itself). We want the pole buoy to be stable, but also to
have sufficient height for viewing (for retrieval!) and for good GPS
transmission.

Mark the top/bottom position of the crab floats on the pole.

Put thru-bolts above and below the crab floats to secure them in place.

------------------------------------------------------------------------

See [Alternative Pole Buoy
Configurations](https://sael-swfsc.github.io/adrift-field-methods/content/Hardware-Alt-PoleBuoy.html#alternative-pole-buoy-configurations)
for previous/alternative Pole Buoy configurations
