---
title: Alternative Pole Buoy Configurations and Assembly Steps
---

## Configurations

## Assembly

1.  Basic Assembly

    1.  Put crab floats on pole (flat ends to each other in the middle). Add tape, hose clamp or other temporary device to hold floats in place. If the center hole of the crab float is not wide enough to fit over the pole, an auger can be used to drill out the middle (ask for more help).

    2.  Add weights to one end of the pole at the very bottom. The pole mounted cylindrical weights should be drilled to fit the pole. Once this weight is secured in place, add the 5 lb flexible wire weight over the top of the pole weight.

    3.  Add radar reflector (first) and then insert the Solar GPS mount on top. Drill a hole through all three (pole, radar reflector, and gps mount) and use a thru-bolt to secure in place. Add a locking nut or electrical tape over the top of the nut to reduce chance of nut working itself loose.

    4.  Add reflector tape near the top of the buoy.

    5.  Add bridle to the pole buoy: 12 strand crab fishing line with 2\@ hose for reducing wear on the line. Tie one end of the line around the pole buoy above the crab floats, and one below the crab floats (with the hose protecting where the line encircles the pole). Tie well and use zip ties to secure the line if needed. Put a loop in the middle of this line so that the surface floats can be clipped onto this loop using a caribiner.

2.  Float test

Put in calm water (at a marina or pool) to determine positioning of the crab floats vertically on the pole. If the floats are too low, the buoy will be unstable (pull the top of the pole over and see how well the buoy rights itself). We want the pole buoy to be stable, but also to have sufficient height for viewing (for retrieval!) and for good GPS transmission.

Mark the top/bottom position of the crab floats on the pole.

Put thru-bolts above and below the crab floats to secure them in place.
