---
title: "Processing Depth Data"
author: "Kourtney Burger"
date: "2024-01-18"
output: html_document
---
```{r}
# library(tidyverse)
# library(chron)
# library(lubridate)
```


# OVERVIEW
1. Read in raw depth data
2. Add column names and additional depth/time columns
3. Fill in columns to calculate depth and date/
4. Remove unnecessary columns and export final data

# 1. Read in raw depth data
```{r}
#set temporary working directory
setwd('Z:\\METADATA\\ADRIFT\\ADRIFT_108\\ADRIFT_108_Depth_Sensus')

#Read in data
#rawDepth <- read.csv('ADRIFT_108_Bottom_Depth_Sensus.csv', header = FALSE)
rawDepth <- read.csv('ADRIFT_108_Top_Depth_Sensus.csv', header = FALSE)
#rawDepth <- read.csv('U-16656.csv', header = FALSE)
#write.csv(rawDepth, "Z:\\METADATA\\ADRIFT\\ADRIFT_108\\ADRIFT_108_Depth_Sensus\\ADRIFT_108_Bottom_Depth_Sensus_RAW.csv", row.names = FALSE)
write.csv(rawDepth, "Z:\\METADATA\\ADRIFT\\ADRIFT_108\\ADRIFT_108_Depth_Sensus\\ADRIFT_108_Top_Depth_Sensus_RAW.csv", row.names = FALSE)
```

# 2. Add column names and additional depth/time columns
```{r}
#Add other columns
rawDepth <- rawDepth %>%
  add_column(Depth_m = NA, Temp_C = NA, Start_Time_UTC = NA, Start_Date_UTC = NA, DateTime_UTC = NA)

#Add column names
colnames(rawDepth) <- c('Leg','Sensus ID','','Year','Month','Day','StartHr UTC','StartMin UTC','StartSec UTC','Elapsed Sec','mBar','degK','Depth_m','Temp_C','Start_Time_UTC','Start_Date_UTC','DateTime_UTC')
```

# 3. Fill in columns to calculate depth and date/time
```{r}
# Calculate depth using pressure (mBar)
for (i in 1:nrow(rawDepth)) {
  rawDepth$Depth_m[i] <- (rawDepth$mBar[i]-992)/103
}

# Convert temperature from Kelvin to Celsius
for (i in 1:nrow(rawDepth)) {
  rawDepth$Temp_C[i] <- rawDepth$degK[i]-273.15
}

# Add start date column
for (i in 1:nrow(rawDepth)) {
  rawDepth$Start_Date_UTC[i] <- paste(rawDepth$Year[i],"-",rawDepth$Month[i],"-",rawDepth$Day[i], sep = "")
}

# rawDepth$Year <- as.integer(rawDepth$Year)
# rawDepth$Month <- as.integer(rawDepth$Month)
# rawDepth$Day <- as.integer(rawDepth$Day)
# 
# rawDepth %>%
#   select(Year, Month, Day) %>%
#   mutate(Start_Date_UTC = make_date(Year, Month, Day))


# Add start time column
for (i in 1:nrow(rawDepth)) {
  rawDepth$Start_Time_UTC[i] <- paste(rawDepth$`StartHr UTC`[i],":",rawDepth$`StartMin UTC`[i],":",rawDepth$`StartSec UTC`[i], sep = "")
}

# Add date/time column
for(i in 1:nrow(rawDepth)) {
  rawDepth$DateTime_UTC[i] <- paste(rawDepth$Start_Date_UTC[i]," ",rawDepth$Start_Time_UTC[i])
}

rawDepth$DateTime_UTC <- as.POSIXct(rawDepth$DateTime_UTC, format = "%Y-%m-%d %H:%M:%S")

for (i in 1:nrow(rawDepth)) {
  rawDepth$DateTime_UTC[i] <- rawDepth$DateTime_UTC[1] + rawDepth$`Elapsed Sec`[i]
}
```

# 4. Remove unnecessary columns and export final data
```{r}
finalDepth <- subset(rawDepth, select = c("Sensus ID","DateTime_UTC","mBar","degK","Depth_m","Temp_C"))
```

```{r}
#write.csv(finalDepth, "Z:\\METADATA\\ADRIFT\\ADRIFT_108\\ADRIFT_108_Depth_Sensus\\ADRIFT_108_Bottom_Depth_Sensus.csv", row.names=FALSE)
write.csv(finalDepth, "Z:\\METADATA\\ADRIFT\\ADRIFT_108\\ADRIFT_108_Depth_Sensus\\ADRIFT_108_Top_Depth_Sensus.csv", row.names=FALSE)
```

